FROM node:14

WORKDIR /frontend
COPY ./frontend/. ./

RUN npm install
RUN npm install -g serve
RUN REACT_APP_SERVER_IP=localhost \
    REACT_APP_PORT=5005 \
    npm run build

EXPOSE 3000
CMD ["serve", "-s", "build"]
